-- =====================================================================
-- club-data : ข้อมูลอ้างอิงของระบบ (ไม่ใช่ข้อมูลสมาชิก)
-- สำรองเมื่อ 2026-10-01
-- รันหลัง schema.sql หรือหลัง migrations/ ครบแล้ว
-- ใช้ on conflict do nothing จึงรันซ้ำได้ ไม่ทับค่าที่มีอยู่
-- =====================================================================

-- ประเภทหน่วยงาน (public.org_types)
insert into public.org_types select * from json_populate_record(null::public.org_types, '{"code": "pho", "name": "สำนักงานสาธารณสุขจังหวัด", "sort_order": 10, "requires_text": false, "active": true}') on conflict (code) do nothing;
insert into public.org_types select * from json_populate_record(null::public.org_types, '{"code": "dho", "name": "สำนักงานสาธารณสุขอำเภอ", "sort_order": 20, "requires_text": false, "active": true}') on conflict (code) do nothing;
insert into public.org_types select * from json_populate_record(null::public.org_types, '{"code": "hospital", "name": "โรงพยาบาล", "sort_order": 30, "requires_text": false, "active": true}') on conflict (code) do nothing;
insert into public.org_types select * from json_populate_record(null::public.org_types, '{"code": "hpht", "name": "โรงพยาบาลส่งเสริมสุขภาพตำบล", "sort_order": 40, "requires_text": false, "active": true}') on conflict (code) do nothing;
insert into public.org_types select * from json_populate_record(null::public.org_types, '{"code": "sanh", "name": "สถานีอนามัยเฉลิมพระเกียรติ 60 พรรษา นวมินทราชินี", "sort_order": 50, "requires_text": false, "active": true}') on conflict (code) do nothing;
insert into public.org_types select * from json_populate_record(null::public.org_types, '{"code": "local_gov", "name": "องค์กรปกครองส่วนท้องถิ่น", "sort_order": 60, "requires_text": false, "active": true}') on conflict (code) do nothing;
insert into public.org_types select * from json_populate_record(null::public.org_types, '{"code": "school", "name": "สถานศึกษา", "sort_order": 70, "requires_text": false, "active": true}') on conflict (code) do nothing;
insert into public.org_types select * from json_populate_record(null::public.org_types, '{"code": "private", "name": "ภาคเอกชน", "sort_order": 80, "requires_text": false, "active": true}') on conflict (code) do nothing;
insert into public.org_types select * from json_populate_record(null::public.org_types, '{"code": "other", "name": "อื่นๆ", "sort_order": 999, "requires_text": true, "active": true}') on conflict (code) do nothing;

-- ตั้งค่าระบบ (public.settings)
insert into public.settings select * from json_populate_record(null::public.settings, '{"key": "bank", "value": {"note": "กรุณาโอนตามจำนวนที่ระบุ และเก็บสลิปไว้เพื่อแนบในระบบ", "bank_name": "ธนาคารกรุงไทย", "account_no": "3083210809", "account_name": "นายสังคม ลำไธสง และน.ส.กรองกาญจน์ ผ่ายภูเขียว และนางพักตร์พิไล เตนากุล", "promptpay_id": "", "promptpay_type": "phone"}, "is_public": true, "description": "บัญชีรับชำระค่าสมัคร (ผู้ดูแลต้องกรอกเลขบัญชี/พร้อมเพย์ก่อนเปิดใช้งาน)", "updated_at": "2026-09-17T02:38:22.009+00:00", "updated_by": null}') on conflict (key) do nothing;
insert into public.settings select * from json_populate_record(null::public.settings, '{"key": "club", "value": {"name": "ชมรมอนามัยสิ่งแวดล้อมจังหวัดบุรีรัมย์", "email": "envburiram@gmail.com", "phone": "0 4461 1562 ต่อ 127", "address": "ชมรมอนามัยสิ่งแวดล้อมจังหวัดบุรีรัมย์ สำนักงานสาธารณสุขจังหวัดบุรีรัมย์ เลขที่ 261 ถนนจิระ ตำบลในเมือง อำเภอเมืองบุรีรัมย์ จังหวัดบุรีรัมย์ 31000", "name_en": "Buriram Environmental Health Club", "registrar": "", "short_name": "ชมรมอนามัยสิ่งแวดล้อมจังหวัดบุรีรัมย์"}, "is_public": true, "description": "ข้อมูลชมรมที่แสดงบนบัตรสมาชิกและใบสำคัญรับเงิน (ผู้ดูแลแก้ไขได้)", "updated_at": "2026-09-17T02:38:22.009+00:00", "updated_by": null}') on conflict (key) do nothing;
insert into public.settings select * from json_populate_record(null::public.settings, '{"key": "fees", "value": {"new": 100, "renew": 100}, "is_public": true, "description": "ค่าธรรมเนียม: new = สมัครใหม่, renew = ต่ออายุ (บาท)", "updated_at": "2026-09-17T02:38:22.009+00:00", "updated_by": null}') on conflict (key) do nothing;
insert into public.settings select * from json_populate_record(null::public.settings, '{"key": "legal", "value": {"dpo_email": "envburiram@gmail.com", "terms_version": "1.0", "privacy_version": "1.0", "retention_years": 5}, "is_public": true, "description": "เวอร์ชันเอกสารทางกฎหมายและระยะเวลาเก็บข้อมูล", "updated_at": "2026-09-17T02:38:22.009+00:00", "updated_by": null}') on conflict (key) do nothing;
insert into public.settings select * from json_populate_record(null::public.settings, '{"key": "membership", "value": {"term_years": 1, "renew_window_days": 30}, "is_public": true, "description": "อายุบัตรสมาชิก (ปี) และช่วงวันที่เปิดให้ต่ออายุก่อนหมดอายุ", "updated_at": "2026-09-17T02:38:22.009+00:00", "updated_by": null}') on conflict (key) do nothing;
insert into public.settings select * from json_populate_record(null::public.settings, '{"key": "signatories", "value": {"receipt_name": "นางสาวกรองกาญจน์  ผ่ายภูเขียว", "president_name": "นายสังคม  ลำไธสง", "president_position": "นักวิชาการสาธารณสุขชำนาญการพิเศษ", "receipt_signature_path": "club/receipt-1789613332031.png", "president_signature_path": "club/president-1789612530525.png"}, "is_public": true, "description": "ชื่อ ตำแหน่ง และไฟล์ลายเซ็นของผู้ลงนามบนบัตรสมาชิกและใบสำคัญรับเงิน", "updated_at": "2026-09-17T13:02:18.095852+00:00", "updated_by": null}') on conflict (key) do nothing;
insert into public.settings select * from json_populate_record(null::public.settings, '{"key": "slip_check", "value": {"require_qr": false, "max_age_days": 30, "enforce_server": true, "min_score_auto_flag": 100, "allow_amount_tolerance": 0}, "is_public": true, "description": "เกณฑ์ตรวจสอบสลิปอัตโนมัติ", "updated_at": "2026-09-17T02:38:22.009+00:00", "updated_by": null}') on conflict (key) do nothing;
insert into public.settings select * from json_populate_record(null::public.settings, '{"key": "slip_verify", "value": {"enabled": true, "provider": "slipok", "require_account_match": true, "auto_reject_on_mismatch": false, "auto_approve_on_verified": true}, "is_public": false, "description": "การยืนยันสลิปกับธนาคาร (อ่านได้เฉพาะผู้ดูแล)", "updated_at": "2026-09-23T02:51:01.448988+00:00", "updated_by": null}') on conflict (key) do nothing;
